string = input('Please enter new sentence: ')
print(string.title())
print(string.capitalize())
print(string.islower())
print(string.swapcase())
print(string.isprintable())
print(string.replace('a', 'o'))
